### ISSUE TITLE
Audio parte da solo

### ISSUE THREAD

**Issue by francescobianco** [lucapu88/speed-typer-game#1]
Quando faccio restart dopo una partita o anche quando cancello tutti gli score, parte l'audio di sottofondo anche se in realtà non si dovrebbe sentire perché disattivato con l'apposito tasto di muto in basso a sinistra.

**Comment by lucapu88** [comment]
Sei sicuro? Ho appena provato e a me non lo fa. Riprova assicurandoti che il pulsante indica che è mutato. Altrimenti se si verifica di nuovo, se riesci a mandarmi in video per email. In ogni caso do un’occhiata.

**Comment by lucapu88** [comment]
Ciao ho fatto un pò di prove e non mi succede nulla...anche perchè da quando l'ho creato ho sempre sviluppato con il pulsante che indica il volume spento e non si è mai attivato l'audio da solo durante tutti i tanti test che ho fatto...avvisami se ti ricapita.

**Comment by francescobianco** [comment]
@lucapu88 credo sia un effetto indesiderato della `location.reload()` che intuitivamente sembra fare un refresh della pagina ma in realtà lavora al livello DOM e non al livello HTTP nel browser (Chrome su linux ubuntu 20.04). Quindi magari nella mia situazione quel reload non opera come ci aspettiamo

- https://groups.google.com/a/chromium.org/g/chromium-discuss/c/T3uNqzSiM0Y?pli=1
- https://stackoverflow.com/questions/3715047/how-to-reload-a-page-using-javascript

**Comment by lucapu88** [comment]
Sistemato, il problema era l'autoplay nell'html.
